title: Welcome to my blog
author: chnirt
email: trinhchinchin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  404 Not found.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
